# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from MainMenu import Ui_mw_main_menu

class Ui_ud_login(object):
    def setupUi(self, ud_login):
        ud_login.setObjectName("ud_login")
        ud_login.resize(353, 301)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ud_login.sizePolicy().hasHeightForWidth())
        ud_login.setSizePolicy(sizePolicy)
        ud_login.setMinimumSize(QtCore.QSize(353, 301))
        ud_login.setMaximumSize(QtCore.QSize(353, 301))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        ud_login.setFont(font)
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::AddressBookNew")
        ud_login.setWindowIcon(icon)
        ud_login.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.Netherlands))
        self.frame = QtWidgets.QFrame(parent=ud_login)
        self.frame.setGeometry(QtCore.QRect(2, 110, 351, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gb_user_login = QtWidgets.QGroupBox(parent=self.frame)
        self.gb_user_login.setGeometry(QtCore.QRect(10, 10, 331, 141))
        self.gb_user_login.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.gb_user_login.setObjectName("gb_user_login")
        self.lUserName = QtWidgets.QLabel(parent=self.gb_user_login)
        self.lUserName.setGeometry(QtCore.QRect(11, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.lUserName.setFont(font)
        self.lUserName.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.lUserName.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lUserName.setObjectName("lUserName")
        self.lineedit_user_login = QtWidgets.QLineEdit(parent=self.gb_user_login)
        self.lineedit_user_login.setGeometry(QtCore.QRect(122, 30, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.lineedit_user_login.setFont(font)
        self.lineedit_user_login.setToolTipDuration(1)
        self.lineedit_user_login.setInputMask("")
        self.lineedit_user_login.setText("")
        self.lineedit_user_login.setObjectName("lineedit_user_login")
        self.lineedit_password = QtWidgets.QLineEdit(parent=self.gb_user_login)
        self.lineedit_password.setGeometry(QtCore.QRect(122, 60, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(False)
        font.setKerning(True)
        self.lineedit_password.setFont(font)
        self.lineedit_password.setToolTipDuration(1)
        self.lineedit_password.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDialableCharactersOnly|QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.lineedit_password.setText("")
        self.lineedit_password.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineedit_password.setClearButtonEnabled(False)
        self.lineedit_password.setObjectName("lineedit_password")
        self.lineedit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lPassword = QtWidgets.QLabel(parent=self.gb_user_login)
        self.lPassword.setGeometry(QtCore.QRect(2, 60, 120, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.lPassword.setFont(font)
        self.lPassword.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.lPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lPassword.setObjectName("lPassword")
        self.label_language = QtWidgets.QLabel(parent=self.gb_user_login)
        self.label_language.setGeometry(QtCore.QRect(92, 110, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.label_language.setFont(font)
        self.label_language.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_language.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_language.setObjectName("label_language")
        self.line = QtWidgets.QFrame(parent=self.gb_user_login)
        self.line.setGeometry(QtCore.QRect(9, 90, 311, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.combobox_language = QtWidgets.QComboBox(parent=self.gb_user_login)
        self.combobox_language.setGeometry(QtCore.QRect(210, 110, 111, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.combobox_language.setFont(font)
        self.combobox_language.setObjectName("combobox_language")
        self.combobox_language.addItem("")
        self.combobox_language.addItem("")
        self.combobox_language.addItem("")
        self.lineedit_user_login.raise_()
        self.lUserName.raise_()
        self.lineedit_password.raise_()
        self.lPassword.raise_()
        self.label_language.raise_()
        self.line.raise_()
        self.combobox_language.raise_()
        self.pushbutton_login = QtWidgets.QPushButton(parent=self.frame)
        self.pushbutton_login.setGeometry(QtCore.QRect(70, 153, 131, 31))
        self.pushbutton_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_login.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(180, 180, 180);\n"
"    font-size: 13px;\n"
"    border: bold;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(150, 150, 150);\n"
"    font-size: 13px;\n"
"    border: bold;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::GoHome")
        self.pushbutton_login.setIcon(icon)
        self.pushbutton_login.setObjectName("pushbutton_login")
        self.pushbutton_exit = QtWidgets.QPushButton(parent=self.frame)
        self.pushbutton_exit.setGeometry(QtCore.QRect(210, 153, 131, 31))
        self.pushbutton_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_exit.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(180, 180, 180);\n"
"    font-size: 13px;\n"
"    border: bold;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(150, 150, 150);\n"
"    font-size: 13px;\n"
"    border: bold;\n"
"}\n"
"")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::SystemLogOut")
        self.pushbutton_exit.setIcon(icon)
        self.pushbutton_exit.setObjectName("pushbutton_exit")
        self.frameIcon = QtWidgets.QFrame(parent=ud_login)
        self.frameIcon.setGeometry(QtCore.QRect(2, 4, 351, 101))
        self.frameIcon.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frameIcon.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameIcon.setObjectName("frameIcon")
        self.label_icon = QtWidgets.QLabel(parent=self.frameIcon)
        self.label_icon.setGeometry(QtCore.QRect(7, 4, 331, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon.sizePolicy().hasHeightForWidth())
        self.label_icon.setSizePolicy(sizePolicy)
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap("icons/WeRHere2.png"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setWordWrap(False)
        self.label_icon.setObjectName("label_icon")

        self.retranslateUi(ud_login)
        QtCore.QMetaObject.connectSlotsByName(ud_login)

    def retranslateUi(self, ud_login):
        _translate = QtCore.QCoreApplication.translate
        ud_login.setWindowTitle(_translate("ud_login", "User Login Window"))
        self.gb_user_login.setTitle(_translate("ud_login", "User Login"))
        self.lUserName.setText(_translate("ud_login", "User Name : "))
        self.lineedit_user_login.setPlaceholderText(_translate("ud_login", "User Name"))
        self.lineedit_password.setPlaceholderText(_translate("ud_login", "Password"))
        self.lPassword.setText(_translate("ud_login", "Password: "))
        self.label_language.setText(_translate("ud_login", "Languages:"))
        self.combobox_language.setItemText(0, _translate("ud_login", "English"))
        self.combobox_language.setItemText(1, _translate("ud_login", "Nederlands"))
        self.combobox_language.setItemText(2, _translate("ud_login", "Türkçe"))
        self.pushbutton_login.setText(_translate("ud_login", "Login"))
        self.pushbutton_login.setShortcut(_translate("ud_login", "Return"))
        self.pushbutton_exit.setText(_translate("ud_login", "Exit"))
        self.pushbutton_exit.setShortcut(_translate("ud_login", "Ctrl+E"))
        self.pushbutton_login.clicked.connect(self.Login)
        self.pushbutton_exit.clicked.connect(self.Exit)
    
    def Login(self):
         
        user_name = self.lineedit_user_login.text()
        password = self.lineedit_password.text()
        self.language = self.combobox_language.currentText()
        if user_name == "admin" and password == "admin":
            self.mw_main_menu = QtWidgets.QMainWindow()
            self.ui = Ui_mw_main_menu()
            self.ui.user = "admin"
            self.ui.setupUi(self.mw_main_menu)
            widgets.addWidget(self.mw_main_menu)
            widgets.setCurrentIndex(widgets.currentIndex()+1)
        elif user_name == "user" and password == "user":
            self.mw_main_menu = QtWidgets.QMainWindow()
            self.ui = Ui_mw_main_menu()
            self.ui.user = "user"
            self.ui.setupUi(self.mw_main_menu)
            widgets.addWidget(self.mw_main_menu)
            widgets.setCurrentIndex(widgets.currentIndex()+1)
        else:
            self.label_error = QtWidgets.QLabel(parent=self.frame)
            self.label_error.setGeometry(QtCore.QRect(70, 110, 251, 31))
            self.label_error.setStyleSheet("color: rgb(255, 0, 0);")
            self.label_error.setText("User Name or Password is incorrect!")
            self.label_error.setObjectName("label_error")
            self.label_error
    def Exit(self):
        QtWidgets.QApplication.quit()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ud_login = QtWidgets.QDialog()
    ui = Ui_ud_login()
    ui.setupUi(ud_login)
    widgets= QtWidgets.QStackedWidget()
    widgets.addWidget(ud_login)
    widgets.show()
    sys.exit(app.exec())
